#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\redirect_me https:\\github.com\Brendabett permanent;/" /etc/nginx/sites-available/default
service nginx start
